### PR TITLE
Tasks panya

### PR DESCRIPTION
**Pull request by naienko**

### CODE REVIEW

**Review by BrianBNeal — DISMISSED** [review]
👍 I tested it out and couldn't find any issues

**Review by katfree — CHANGES_REQUESTED** [review]
Considering defining userId inside of APIManager and adding the search query code to the API manager as well. :)

**Review by katfree — APPROVED** [review]
😄

**Comment by BrianBNeal** [comment]
👍  👍 even better than before

**Review by BrianBNeal — COMMENTED** [review]
do it to it!

**Review by BrianBNeal — APPROVED** [review]
seriously this time

**Comment by katfree** [comment]
> do it to it!

🏃🏻

**Pull request merged**
